const whatsappNumber = "5521975003419";
const whatsappUrl = (message) => `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;

const state = {
  step: "identity", birthName: "", dailyName: "", birthDate: "",
  answers: { area: "", repetition: "", pressure: "", energy: "", nameFeeling: "", desire: "", readiness: "", centralQuestion: "" }
};

const groups = { 1: "AIJQY", 2: "BKR", 3: "CGLS", 4: "DMT", 5: "EHN", 6: "UVWXÇ", 7: "OZ", 8: "FP" };
const baseValues = {};
Object.entries(groups).forEach(([value, letters]) => [...letters].forEach((letter) => { baseValues[letter] = Number(value); }));
const accents = {
  Á:["A","add",2], É:["E","add",2], Í:["I","add",2], Ó:["O","add",2], Ú:["U","add",2],
  Ã:["A","add",3], Õ:["O","add",3], Â:["A","add",7], Ê:["E","add",7], Ô:["O","add",7],
  À:["A","double",0], È:["E","double",0], Ì:["I","double",0], Ò:["O","double",0], Ù:["U","double",0],
  Ä:["A","double",0], Ë:["E","double",0], Ï:["I","double",0], Ö:["O","double",0], Ü:["U","double",0]
};
const profiles = {
  0:{title:"potencial ainda sem forma",light:"Esse zero não fala de vazio. Ele mostra uma força que ainda precisa ser reconhecida antes de receber um nome simples.",shadow:"Na sombra, você pode sentir que algo existe por dentro, mas não encontra uma forma clara de se manifestar.",truth:"O que ainda não ganhou forma não deixou de existir. Precisa de escuta antes de direção.",arcana:"O Louco",integration:"Eu trabalharia presença, começo e autorização para descobrir o caminho enquanto você caminha."},
  1:{title:"autoria e começo",light:"No lado luz, você reconhece a própria vontade, abre caminhos e não espera que alguém autorize a sua existência.",shadow:"No lado sombra, pode tentar provar independência o tempo inteiro e transformar autonomia em solidão, pressa ou dificuldade de receber ajuda.",truth:"O 1 não te pede para viver sozinho. Ele te pede para parar de abandonar a si mesmo quando chega a hora de escolher.",arcana:"O Mago",integration:"Eu trabalharia o direito de iniciar, sustentar decisões e ocupar espaço sem pedir desculpas por existir."},
  2:{title:"escuta e vínculo",light:"No lado luz, você percebe nuances, aproxima pessoas e escuta até o que não foi dito. Existe delicadeza e uma inteligência emocional muito fina aqui.",shadow:"No lado sombra, essa sensibilidade pode virar medo de conflito, dependência de aprovação e o hábito de sentir todo mundo antes de sentir a si mesmo.",truth:"O 2 amadurece quando vínculo deixa de significar anulação. A paz que exige o seu silêncio não é paz; é desaparecimento.",arcana:"A Sacerdotisa",integration:"Eu cuidaria dos vínculos, dos limites e da sua capacidade de permanecer sensível sem se tornar refém do ambiente."},
  3:{title:"voz e criação",light:"No lado luz, você transforma sensação em palavra, beleza, humor e presença. Quando se permite aparecer, a sua expressão desperta vida nos outros.",shadow:"No lado sombra, pode esconder dor atrás de um sorriso, falar muito sem se revelar ou se criticar tanto que a criação morre antes de chegar ao mundo.",truth:"O 3 não quer performance. Quer verdade em movimento. A sua voz não precisa ser perfeita; precisa estar viva.",arcana:"A Imperatriz",integration:"Eu trabalharia voz, espontaneidade, vergonha e o medo de ser visto exatamente como você é."},
  4:{title:"estrutura e construção",light:"No lado luz, você dá corpo às ideias. Organiza o caos, cria método e transmite uma firmeza que faz as pessoas sentirem que existe chão.",shadow:"No lado sombra, responsabilidade pode virar rigidez, controle e uma cobrança silenciosa para dar conta de tudo.",truth:"O 4 não veio te condenar ao peso. Veio te ensinar que constância também inclui pausa, prazer e espaço para o inesperado.",arcana:"O Imperador",integration:"Eu trabalharia controle, sobrecarga, rotina, materialização e o direito de construir sem se endurecer."},
  5:{title:"movimento e liberdade",light:"No lado luz, você renova ambientes, aprende pela experiência e reconhece quando a vida precisa circular.",shadow:"No lado sombra, liberdade pode virar fuga, excesso, impulsividade ou dificuldade de permanecer tempo suficiente para uma escolha criar raiz.",truth:"O 5 pede liberdade com consciência: mudar porque a alma cresceu, não apenas porque ficar começou a doer.",arcana:"O Papa",integration:"Eu trabalharia medo do novo, dispersão, excessos e a construção de uma liberdade que não destrua o que você ama."},
  6:{title:"cuidado e pertencimento",light:"No lado luz, você cria beleza, acolhimento e responsabilidade afetiva. Tem capacidade de transformar ambientes em casa.",shadow:"No lado sombra, amor pode se confundir com obrigação, culpa e necessidade de salvar.",truth:"O 6 te lembra que receber também é uma forma de amar. Você não precisa adoecer de cuidado para provar que o seu afeto é verdadeiro.",arcana:"Os Enamorados",integration:"Eu trabalharia amor próprio, culpa, pertencimento e o equilíbrio entre oferecer e permitir-se receber."},
  7:{title:"profundidade e fé",light:"No lado luz, você atravessa aparências, investiga e procura uma verdade que tenha raiz.",shadow:"No lado sombra, profundidade pode virar desconfiança, ceticismo e afastamento.",truth:"O 7 não te pede fé cega. Pede uma inteligência capaz de aceitar que nem tudo o que é verdadeiro cabe numa prova.",arcana:"O Carro",integration:"Eu trabalharia confiança, isolamento, excesso mental e a reconexão entre a sua inteligência e a sua experiência espiritual."},
  8:{title:"poder e materialização",light:"No lado luz, você administra força, recursos e escolhas com potência de realização.",shadow:"No lado sombra, dinheiro, controle e resultado podem ocupar espaço demais. Você pode trabalhar até a exaustão ou diminuir a própria potência por medo do julgamento.",truth:"O 8 quer que você aprenda a sustentar o poder com justiça, consciência e merecimento.",arcana:"A Justiça",integration:"Eu trabalharia prosperidade, preço, autoridade, merecimento e a permissão de crescer sem trair quem você é."},
  9:{title:"síntese e encerramento",light:"No lado luz, você enxerga além do óbvio, compreende travessias e transforma experiência em consciência.",shadow:"No lado sombra, pode carregar histórias que já terminaram, salvar pessoas que não pediram salvação e sentir um cansaço antigo.",truth:"O 9 não veio carregar o mundo. Veio aprender a amar também através da devolução, do limite e do encerramento.",arcana:"O Eremita",integration:"Eu trabalharia despedidas, ressentimentos, excesso de responsabilidade espiritual e a coragem de deixar morrer o que já cumpriu seu ciclo."}
};
const numberRoles={
  "Motivação":{opening:"A Motivação é o desejo que se move por baixo das suas escolhas. É o que a sua alma procura quando ninguém está olhando.",bridge:"Quando esse número é reprimido, você pode conquistar muita coisa e ainda sentir que falta algo que não sabe nomear."},
  "Impressão":{opening:"A Impressão é a energia que chega antes das suas palavras. É a forma como o mundo encontra você e, muitas vezes, a armadura que aprendeu a vestir.",bridge:"Nem sempre o que as pessoas enxergam é tudo o que você é. Aqui existe uma diferença entre presença verdadeira e proteção automática."},
  "Expressão":{opening:"A Expressão mostra como o seu dom deseja ganhar corpo. É a ferramenta que você recebeu para existir, criar e deixar uma marca concreta.",bridge:"É aqui que potencial encontra matéria. Quando você assume essa força, a sua presença começa a organizar caminhos."},
  "Destino":{opening:"O Destino é a estrada que a sua alma escolheu atravessar nesta encarnação. Não é uma sentença. É a experiência que insiste em ensinar até virar consciência.",bridge:"Essa estrada reaparece em pessoas, rupturas, oportunidades e recomeços até que a lição deixe de ser peso e vire sabedoria."},
  "Missão":{opening:"A Missão é o encontro entre a estrada e a ferramenta. Mostra o que você veio realizar quando para de viver só para sobreviver.",bridge:"Missão não é trabalhar sem parar nem salvar todo mundo. É dar forma ao que tem verdade, presença e continuidade."}
};
const sequenceReadings = {
  1:{title:"O Bloqueio da Iniciativa",shadow:"A dependência",lived:"Se o 111 apareceu, provavelmente você começa com força, mas duvida quando precisa continuar sozinho. Pode esperar aprovação, pedir sinais demais ou se diminuir para não desagradar.",block:"Essa repetição concentra a identidade e pode bloquear a coragem de decidir, a autonomia e a liderança da própria vida.",layers:["Na camada visível, aparece como indecisão, projetos interrompidos ou medo de se expor.","Na camada emocional, existe o receio de escolher e perder amor, apoio ou pertencimento.","Na camada profunda, a alma está reaprendendo a dizer: eu existo, eu escolho e eu sustento."],gift:"Dentro desse bloqueio existe autoria. Quando o 1 deixa de pedir licença, ele vira presença, iniciativa e direção.",treatment:"Eu investigaria na Radiestesia onde a sua decisão perde força, trabalharia autonomia na Mesa Radiônica e levaria essa escolha para uma vivência xamânica de retomada do próprio lugar."},
  2:{title:"O Bloqueio da União",shadow:"A sensibilidade excessiva",lived:"Se o 222 apareceu, provavelmente você se magoa com facilidade, sente o clima antes de todo mundo e engole muita coisa para evitar conflito.",block:"Essa repetição pode bloquear cooperação saudável, paciência real e relação sem dependência emocional.",layers:["Na superfície, aparece como medo de briga, carência ou necessidade de confirmação.","Por baixo, existe hipervigilância: você tenta prever o outro para não ser abandonado.","Na raiz, o aprendizado é continuar sensível sem abandonar a própria verdade."],gift:"O dom preso é uma escuta extraordinária. Quando existe limite, a sensibilidade deixa de ferir e começa a orientar.",treatment:"Eu usaria Reiki para acalmar o excesso de absorção, Radiestesia para investigar vínculos e Mesa Radiônica para reorganizar dependência, ressentimento e limite."},
  3:{title:"O Bloqueio da Expressão",shadow:"A voz travada",lived:"Se o 333 apareceu, provavelmente você guarda o que sente e tenta disfarçar a dor com um sorriso. Pode ter medo do julgamento, revisar tudo mil vezes e achar que nunca está bom.",block:"Essa repetição pode bloquear criatividade, alegria genuína e comunicação da verdade interior.",layers:["Na camada visível, você se cala, se explica demais ou cria sem conseguir mostrar.","Na camada emocional, existe vergonha: o medo de que a sua verdade seja demais.","Na camada ancestral, pode existir memória de crítica, silenciamento ou punição por ter voz."],gift:"O mesmo lugar que trava a voz guarda palavra, arte, presença e capacidade de tocar pessoas.",treatment:"Eu investigaria a origem desse silenciamento na Radiestesia, limparia registros de crítica na Mesa e trabalharia voz, corpo e expressão nas vivências xamânicas e reprogramações."},
  4:{title:"O Bloqueio da Estrutura",shadow:"O caos interno",lived:"Se o 444 apareceu, provavelmente você oscila entre procrastinar e se matar de trabalhar. Pode controlar tudo porque teme que qualquer relaxamento faça a vida desabar.",block:"Essa repetição pode bloquear materialização, estabilidade e construção de bases sólidas sem transformar a vida numa prisão.",layers:["Na superfície, aparece como desorganização, rigidez ou sobrecarga.","Por baixo, existe medo de falhar e a sensação de que descansar é perder o controle.","Na raiz, a alma aprende que estrutura serve à vida; não existe para castigá-la."],gift:"O dom preso é a capacidade de construir algo duradouro. Quando o 4 respira, método deixa de ser peso.",treatment:"Eu trabalharia na Mesa os padrões de esforço sem retorno, usaria Radiestesia para localizar vazamentos e reprogramações para separar disciplina de autocastigo."},
  5:{title:"O Bloqueio da Mudança",shadow:"O medo do novo",lived:"Se o 555 apareceu, provavelmente uma parte sua deseja liberdade enquanto outra se agarra ao conhecido, mesmo quando já está infeliz.",block:"Essa repetição pode bloquear liberdade consciente, adaptação e coragem de atravessar o novo.",layers:["Na superfície, aparece como tédio, impulsividade, vícios ou relações sem raiz.","Na camada emocional, existe medo de perder segurança e medo de ser aprisionado.","Na raiz, o aprendizado é mover-se por escolha, não apenas por fuga."],gift:"O potencial é renovação. O 5 maduro sabe mudar sem destruir tudo.",treatment:"Eu investigaria medos e excessos pela Radiestesia, trabalharia fugas na Mesa e marcaria a travessia do velho para o novo em uma abertura xamânica."},
  6:{title:"O Bloqueio do Amor Próprio",shadow:"A autocobrança tóxica",lived:"Se o 666 apareceu, provavelmente você se compara, se cobra perfeição e cuida de todo mundo antes de perceber que está vazio.",block:"Essa repetição pode bloquear harmonia interna, autoestima e relações equilibradas.",layers:["Na superfície, aparece como culpa, comparação e exaustão afetiva.","Por baixo, existe a crença de que é preciso merecer amor sendo útil ou impecável.","Na raiz, a alma aprende que pertencimento não deveria exigir autoabandono."],gift:"O dom preso é a medicina do cuidado. Quando começa por você, acolhe sem salvar e ama sem se perder.",treatment:"Eu usaria Reiki para recompor o campo, Mesa para trabalhar culpa e merecimento e vivências xamânicas para devolver cargas familiares que nunca foram suas."},
  7:{title:"O Bloqueio da Fé",shadow:"O ceticismo e a solidão",lived:"Se o 777 apareceu, provavelmente você se sente sozinho mesmo acompanhado. Pode racionalizar o que sente e construir distância porque acredita que ninguém alcança a sua profundidade.",block:"Essa repetição pode bloquear conexão espiritual, intuição, confiança e pertencimento.",layers:["Na superfície, aparece como isolamento, crises existenciais e excesso de análise.","Na camada emocional, existe medo de confiar e ser decepcionado.","Na raiz, a alma procura reconciliar inteligência e mistério."],gift:"O potencial é uma espiritualidade lúcida e profunda. A solidão pode virar templo, não exílio.",treatment:"Eu investigaria confiança na Radiestesia, harmonizaria o excesso mental com Reiki e criaria uma abertura xamânica segura."},
  8:{title:"O Bloqueio da Prosperidade",shadow:"A escassez e o poder",lived:"Se o 888 apareceu, provavelmente dinheiro e poder mexem profundamente com você. Pode trabalhar até a exaustão, ter medo de cobrar ou buscar controle material para não se sentir vulnerável.",block:"Essa repetição pode bloquear abundância, poder legítimo, reconhecimento e justiça na troca.",layers:["Na superfície, aparece como dívida, preço baixo, compulsão por resultado ou conflito com autoridade.","Por baixo, existe medo de crescer, ser julgado ou repetir abusos de poder.","Na raiz, a alma aprende que prosperar com consciência não trai a espiritualidade."],gift:"O dom preso é materialização com liderança.",treatment:"Eu abriria uma Radiestesia de prosperidade, trabalharia preço e merecimento na Mesa e usaria reprogramações para separar dinheiro de culpa."},
  9:{title:"O Bloqueio do Perdão",shadow:"O ressentimento",lived:"Se o 999 apareceu, provavelmente você carrega mágoas antigas como se tivessem acontecido ontem e mantém vínculos encerrados dentro de si.",block:"Essa repetição pode bloquear encerramento, sabedoria, perdão e leveza.",layers:["Na superfície, aparece como nostalgia dolorosa ou dificuldade de despedida.","Na camada emocional, existe a sensação de que soltar apagaria o que aconteceu.","Na raiz, a alma aprende que encerrar muda o lugar que o passado ocupa."],gift:"O potencial é transmutação: transformar cicatriz em consciência.",treatment:"Eu trabalharia encerramentos na Mesa, investigaria vínculos ativos pela Radiestesia e conduziria um ritual xamânico de devolução e passagem."}
};
const services={
  mapa:{number:"01",title:"Mapa da Alma Xamânica",tone:"green",action:"Quero meu mapa completo",investment:"R$ 497",duration:"Produção autoral em até 10 dias úteis",includes:"Mapa digital completo, análise de até 3 correções vibracionais e encontro online de entrega de até 75 minutos.",opening:"Este não é um relatório sobre características. Eu abro a matemática do seu nome para encontrar força, ferida, memória e direção. O mapa mostra onde você se abandona, o que a linhagem ainda repete e qual identidade quer nascer agora.",forYou:"Este trabalho chama quando os mesmos ciclos mudam de rosto, mas terminam no mesmo lugar; quando o nome parece não caber mais; quando você quer compreender missão, ancestralidade, prosperidade, relações ou uma nova assinatura sem respostas genéricas.",process:"Eu cruzo Numerologia Cabalística, Pirâmide da Vida, sequências reais, respostas do questionário, ciclos e Arcanos. A Radiestesia pode entrar nos bastidores para conferir prioridades e compatibilidades.",movement:"Você recebe linguagem para reconhecer a própria história, uma direção prática e um plano para que o que foi compreendido não volte a ficar preso no papel.",journey:[["Antes","Você envia seus nomes, data, questão central e responde ao questionário de escuta. Eu confiro a grafia antes de calcular."],["Durante","Eu calculo, audito a Pirâmide inteira, encontro repetições, cruzo o mapa com a sua história e testo correções sem escolher nome apenas pela soma final."],["Na entrega","A gente se encontra online. Eu leio com você, explico os pontos centrais e abro espaço para as perguntas."],["Depois","Você permanece com o documento, as assinaturas testadas e um plano de integração."]],deliverables:["Mapa autoral diagramado e personalizado","Pirâmide completa e sequências verificadas","Potência, sombra e Arcano dos números centrais","Lições, Dívidas, ausências, excessos e ciclos","Análise ancestral e direção evolutiva","Até 3 correções de nome recalculadas por inteiro","Paleta numerológica e práticas de integração","Indicação terapêutica ligada ao que apareceu"],aftercare:"Se o mapa mostrar um ponto que pede acompanhamento, eu explico por quê e qual cuidado pode servir. Você decide se quer seguir. A leitura não cria obrigação de contratar outro processo."},
  tarot:{number:"02",title:"Tarot de Direção",tone:"amber",action:"Quero abrir uma questão",investment:"R$ 147",duration:"Encontro online de até 60 minutos",includes:"Leitura aprofundada de uma questão central, desdobramentos necessários e síntese do movimento indicado pelas cartas.",opening:"Eu não uso o Tarot para decidir a sua vida. Uso para revelar a força que está conduzindo a situação, aquilo que você ainda não consegue enxergar e a escolha que devolve movimento.",forYou:"Este atendimento chama quando você está dividido, repetindo uma relação, diante de uma decisão ou sentindo que existe uma verdade no campo que ainda não conseguiu nomear.",process:"A gente começa pela sua questão. Eu abro as cartas para ler potência, sombra, repetição, movimento e consequência possível das escolhas. Não alimento vigilância sobre a vida alheia e não retiro o seu livre-arbítrio.",movement:"A intenção é que você saia menos preso à ansiedade e mais capaz de reconhecer o que já sabe, o que ainda não viu e qual movimento depende de você.",journey:[["A pergunta","A gente transforma ansiedade difusa numa questão que consiga ser lida com verdade."],["A mesa","Eu leio o que sustenta a situação, onde você perde força e o que muda quando escolhe diferente."],["A conversa","Você participa, reconhece, pergunta e pode contradizer. O Tarot não fala sobre você sem você."],["O movimento","A leitura termina com uma atitude possível, não com dependência de novas previsões."]],deliverables:["Leitura ao vivo de uma questão central","Potência e sombra da situação","Padrão invisível que sustenta a repetição","Caminhos possíveis e consequências prováveis","Orientação prática para o próximo movimento","Espaço para perguntas durante a sessão"],aftercare:"A leitura orienta consciência e escolha; não garante acontecimento nem substitui suporte jurídico, financeiro, médico ou psicológico."},
  mesa:{number:"03",title:"Mesa Radiônica",tone:"clay",action:"Quero reorganizar este ciclo",investment:"R$ 247",duration:"Abertura, tratamento e acompanhamento por 7 dias",includes:"Conversa inicial, investigação radiestésica do tema, operação da Mesa, devolutiva e orientação de integração.",opening:"Tem coisa que a mente já entendeu e mesmo assim o corpo, o vínculo ou a vida continuam repetindo. A Mesa trabalha essa distância entre consciência e campo.",forYou:"Este processo chama quando existem repetições afetivas, bloqueios de trabalho e prosperidade, vínculos difíceis de encerrar, projetos parados, culpa, medo ou sensação de estar preso ao mesmo ciclo.",process:"Primeiro eu escuto a sua questão. A Radiestesia entra como instrumento da Mesa para investigar prioridade, intensidade e compatibilidade. Depois eu limpo, harmonizo e reorganizo frequências relacionadas ao foco.",movement:"O objetivo é retirar ruído, devolver disponibilidade ao campo e criar uma condição mais limpa para que a mudança encontre atitude concreta.",journey:[["A escuta","Você me conta a repetição e o que já tentou. Eu separo desejo, sintoma e foco real."],["A investigação","Eu uso a Radiestesia dentro da Mesa para localizar prioridades e evitar tratamento genérico."],["A operação","O trabalho é realizado a distância sobre um foco acordado e sem interferir no livre-arbítrio de terceiros."],["A integração","Eu entrego a devolutiva e acompanho o período combinado para observar respostas."]],deliverables:["Escuta e definição de um foco central","Investigação radiestésica dentro do processo","Tratamento vibracional personalizado","Devolutiva do que foi encontrado e trabalhado","Orientação para os 7 dias de integração","Canal de acompanhamento no período combinado"],aftercare:"O campo pode responder de formas diferentes. Eu não crio expectativa obrigatória. Se surgir demanda fora do cuidado energético, oriento a busca de profissional habilitado."},
  reiki:{number:"04",title:"Reiki",tone:"violet",action:"Quero harmonizar minha energia",investment:"R$ 147",duration:"Sessão online de até 60 minutos",includes:"Escuta inicial, aplicação energética, aterramento e conversa breve de integração.",opening:"Nem todo momento pede mais análise. Às vezes você já atravessou demais e o campo precisa ser acolhido antes de receber outra resposta.",forYou:"O Reiki chama em fases de cansaço, sensibilidade elevada, luto, transição, ansiedade, depois de processos intensos ou quando você sente que perdeu o próprio centro.",process:"Eu começo te escutando e combinando um foco. A aplicação acontece a distância, num tempo protegido. Ao final, integro percepções sem transformar sensações em diagnóstico.",movement:"A intenção é devolver presença. Não apagar a história nem forçar leveza, mas criar espaço para corpo, emoção e pensamento pararem de disputar atenção.",journey:[["Chegada","A gente nomeia como você está e o que precisa ser sustentado."],["Aplicação","Você recebe o Reiki num espaço de repouso, com orientação para permanecer confortável."],["Aterramento","A gente volta ao corpo, à respiração e ao aqui."],["Integração","Você recebe cuidados leves para as horas seguintes."]],deliverables:["Escuta breve e foco de harmonização","Aplicação individual a distância","Aterramento ao final","Partilha cuidadosa das percepções","Orientação simples para o restante do dia"],aftercare:"Reiki é cuidado complementar. Não substitui tratamento médico ou psicológico e não exige qualquer fenômeno específico para que a sessão tenha valor."},
  xamanismo:{number:"05",title:"Vivências Xamânicas",tone:"night",action:"Quero viver uma travessia",investment:"R$ 297",duration:"Vivência individual de até 90 minutos",includes:"Escuta do tema, ritual autoral de abertura ou encerramento e orientação de integração.",opening:"Existem mudanças que pedem um marco. Um antes e um depois que o corpo reconheça. A vivência cria esse território simbólico e espiritual de passagem.",forYou:"Este trabalho chama quando você precisa encerrar um ciclo, devolver um peso ancestral, retomar força, atravessar um luto, inaugurar uma identidade, ativar um nome ou firmar uma escolha.",process:"Eu desenho a prática a partir da sua questão. Pode envolver abertura, limpeza, devolução, respiração, presença corporal, palavra, elementos naturais e fogo simbólico.",movement:"Você não sai apenas sabendo o que precisa mudar. Sai tendo começado a mudança com o corpo, a palavra e uma atitude concreta.",journey:[["Preparação","Eu conheço a história, reconheço o limite e explico a vivência antes de começar."],["Abertura","Criamos um campo de presença para separar o cotidiano da travessia."],["Travessia","O ritual dá corpo à escolha por meio da palavra, do gesto e dos elementos."],["Retorno","A gente fecha, aterrissa e transforma o símbolo numa atitude possível."]],deliverables:["Conversa de preparação","Ritual individual criado para a questão","Condução de abertura, movimento e fechamento","Orientação de integração","Prática concreta para sustentar a passagem"],aftercare:"Eu não uso terror espiritual, não prometo cura e não invento narrativa sobre a sua vida. A vivência respeita sua autonomia, seu corpo e seus acompanhamentos profissionais."}
};

function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]); }
function reduce(value) { let result = Math.abs(Number(value)); while (result > 9) result = String(result).split("").reduce((sum, digit) => sum + Number(digit), 0); return result; }
function letterValue(letter) { const upper = letter.toLocaleUpperCase("pt-BR"); if (baseValues[upper]) return baseValues[upper]; if (!accents[upper]) return 0; const [baseLetter, mode, amount] = accents[upper]; const base = baseValues[baseLetter]; return mode === "double" ? base * 2 : base + amount; }
function isVowel(letter) { const clean = letter.toLocaleUpperCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g, ""); return "AEIOU".includes(clean); }
function buildPyramid(values) { if (!values.length) return []; const rows = [values.map(reduce)]; while (rows.at(-1).length > 1) { const row = rows.at(-1); rows.push(row.slice(0,-1).map((value,index) => reduce(value + row[index+1]))); } return rows; }
function findSequences(rows) { const hits=[]; rows.forEach((row,rowIndex)=>{ let start=0; while(start<row.length){ let end=start+1; while(end<row.length && row[end]===row[start]) end++; if(end-start>=3) hits.push({number:row[start],line:rowIndex+1,length:end-start}); start=end; } }); return hits; }
function calculate(name,date) {
  const letters=[...name].filter((char)=>letterValue(char)>0); const values=letters.map(letterValue);
  const vowels=letters.reduce((sum,char)=>sum+(isVowel(char)?letterValue(char):0),0); const consonants=letters.reduce((sum,char)=>sum+(!isVowel(char)?letterValue(char):0),0);
  const expression=values.reduce((sum,value)=>sum+value,0); const destiny=date.replace(/\D/g,"").split("").reduce((sum,digit)=>sum+Number(digit),0); const pyramid=buildPyramid(values);
  const counts=values.map(reduce).reduce((acc,value)=>{acc[value]=(acc[value]||0)+1;return acc;},{});
  return {letters,pyramid,sequences:findSequences(pyramid),motivation:reduce(vowels),impression:reduce(consonants),expression:reduce(expression),destiny:reduce(destiny),mission:reduce(reduce(expression)+reduce(destiny)),apex:pyramid.at(-1)?.[0]||0,missing:Array.from({length:8},(_,i)=>i+1).filter((value)=>!counts[value]),tendencies:Object.entries(counts).filter(([,count])=>count>=4).map(([value,count])=>({value:Number(value),count}))};
}
function formatBirthDate(value) { const digits=value.replace(/\D/g,"").slice(0,8); if(digits.length<=2)return digits; if(digits.length<=4)return `${digits.slice(0,2)}/${digits.slice(2)}`; return `${digits.slice(0,2)}/${digits.slice(2,4)}/${digits.slice(4)}`; }

function progressHeader(percent, title="Questionário de escuta") { return `<div class="progress-header"><span>${title}</span><span>${percent}%</span></div><div class="progress-track"><i style="width:${percent}%"></i></div>`; }
function optionGroup(legend,name,options){ return `<fieldset class="question-group"><legend>${legend}</legend><div class="option-grid">${options.map((option)=>`<label class="option"><input type="radio" name="${name}" value="${escapeHtml(option)}"><span>${escapeHtml(option)}</span></label>`).join("")}</div></fieldset>`; }
function setError(message){ const old=document.querySelector(".quiz-error"); if(old) old.remove(); if(message){ const error=document.createElement("div"); error.className="quiz-error"; error.textContent=message; document.querySelector(".quiz-form")?.prepend(error); } }
function readRadio(name){ return document.querySelector(`input[name="${name}"]:checked`)?.value || ""; }

function renderIdentity(){
  state.step="identity"; const panel=document.querySelector("#quiz-panel");
  panel.innerHTML=`${progressHeader(25)}<form class="quiz-form" id="identity-form"><div class="form-opening"><span class="step-number">01</span><div><h3>Primeiro, eu preciso encontrar a raiz do seu nome.</h3><p>Escreva exatamente como está no registro. Acentos alteram o cálculo.</p></div></div><label class="text-field"><span>Nome completo de nascimento</span><input id="birth-name" required placeholder="Ex.: Ana Martins Silva" value="${escapeHtml(state.birthName)}"></label><label class="text-field"><span>Nome que você usa diariamente</span><input id="daily-name" placeholder="Se for diferente" value="${escapeHtml(state.dailyName)}"></label><label class="text-field"><span>Data de nascimento</span><input id="birth-date" type="text" inputmode="numeric" autocomplete="bday" maxlength="10" required placeholder="Digite apenas os números" pattern="[0-9]{2}/[0-9]{2}/[0-9]{4}" value="${escapeHtml(state.birthDate)}"></label><p class="field-helper">Digite os 8 números da sua data. Eu coloco as barras para você.</p><button class="primary-button wide">CONTINUAR A ESCUTA</button></form>`;
  const dateField=document.querySelector("#birth-date"); dateField.addEventListener("input",()=>{dateField.value=formatBirthDate(dateField.value);});
  document.querySelector("#identity-form").addEventListener("submit",(event)=>{event.preventDefault();state.birthName=document.querySelector("#birth-name").value.trim();state.dailyName=document.querySelector("#daily-name").value.trim();state.birthDate=document.querySelector("#birth-date").value.trim();if(!state.birthName||!/^\d{2}\/\d{2}\/\d{4}$/.test(state.birthDate)){setError("Escreva o nome completo e digite os oito números da sua data.");return;}renderListening();});
}

function renderListening(){
  state.step="listening"; const panel=document.querySelector("#quiz-panel");
  panel.innerHTML=`${progressHeader(50)}<form class="quiz-form" id="listening-form"><div class="form-opening"><span class="step-number">02</span><div><h3>Agora eu quero aproximar o cálculo da vida que você está vivendo.</h3><p>Não existe resposta certa. Existe aquilo que está vivo.</p></div></div>${optionGroup("1. Qual área da sua vida mais pede cuidado hoje?","area",["Amor e relações","Trabalho e dinheiro","Família e ancestralidade","Voz e autoestima","Espiritualidade","Direção de vida"])}${optionGroup("2. Qual repetição mais cansa você?","repetition",["Carrego tudo sozinho","Começo e não sustento","Me calo para evitar conflito","Trabalho muito e recebo pouco","Repito relações parecidas","Não consigo encerrar ciclos"])}${optionGroup("3. Quando a pressão aumenta, o que você costuma fazer?","pressure",["Tento controlar tudo","Me isolo","Cuido de todos","Fujo ou me distraio","Paraliso","Reajo e depois me arrependo"])}${optionGroup("4. Como está sua energia neste momento?","energy",["Cansada","Acelerada","Dispersa","Pesada","Sensível","Pronta para mudar"])}<div class="form-navigation"><button type="button" class="back-button" id="back-identity">VOLTAR</button><button class="primary-button">CONTINUAR</button></div></form>`;
  document.querySelector("#back-identity").addEventListener("click",renderIdentity);
  document.querySelector("#listening-form").addEventListener("submit",(event)=>{event.preventDefault();["area","repetition","pressure","energy"].forEach((key)=>state.answers[key]=readRadio(key));if(["area","repetition","pressure","energy"].some((key)=>!state.answers[key])){setError("Escolha uma resposta em cada pergunta para continuar.");return;}renderDirection();});
}

function renderDirection(){
  state.step="direction"; const panel=document.querySelector("#quiz-panel");
  panel.innerHTML=`${progressHeader(75)}<form class="quiz-form" id="direction-form"><div class="form-opening"><span class="step-number">03</span><div><h3>Última camada: o que você está pronto para reconhecer?</h3><p>É aqui que o nome encontra a escolha.</p></div></div>${optionGroup("5. Como você se sente ao ouvir o próprio nome?","nameFeeling",["Representado","Distante","Em conflito","Pesado","Curioso","Nunca pensei nisso"])}${optionGroup("6. O que você mais deseja compreender no mapa?","desire",["Minha missão","Meus bloqueios","Minha ancestralidade","Minha prosperidade","Meus relacionamentos","A força do meu nome"])}${optionGroup("7. Se o mapa apontar uma mudança, como você se sente?","readiness",["Pronto para agir","Quero compreender primeiro","Tenho medo de mudar","Preciso de acompanhamento"])}<label class="text-field"><span>8. Se eu estivesse diante de você agora, qual pergunta você me faria?</span><textarea id="central-question" required rows="4" placeholder="Escreva do seu jeito. Não precisa parecer bonito.">${escapeHtml(state.answers.centralQuestion)}</textarea></label><div class="form-navigation"><button type="button" class="back-button" id="back-listening">VOLTAR</button><button class="primary-button">ABRIR MEU MINI MAPA</button></div></form>`;
  document.querySelector("#back-listening").addEventListener("click",renderListening);
  document.querySelector("#direction-form").addEventListener("submit",(event)=>{event.preventDefault();["nameFeeling","desire","readiness"].forEach((key)=>state.answers[key]=readRadio(key));state.answers.centralQuestion=document.querySelector("#central-question").value.trim();if(["nameFeeling","desire","readiness"].some((key)=>!state.answers[key])||!state.answers.centralQuestion){setError("Escolha as três respostas e escreva a pergunta que está viva em você.");return;}renderResult();});
}

function renderResult(){
  state.step="result"; const result=calculate(state.birthName,state.birthDate); const firstName=(state.dailyName||state.birthName).split(/\s+/)[0]||"você";
  const numbers=[["Motivação",result.motivation],["Impressão",result.impression],["Expressão",result.expression],["Destino",result.destiny],["Missão",result.mission]].map(([label,value])=>`<article><span>${label}</span><strong>${value}</strong></article>`).join("");
  const deepNumbers=[["Motivação",result.motivation],["Impressão",result.impression],["Expressão",result.expression],["Destino",result.destiny],["Missão",result.mission]].map(([label,value])=>{const profile=profiles[value];const role=numberRoles[label];return `<article class="number-deep-reading"><header class="number-reading-head"><div><p class="section-label">${label.toLocaleUpperCase("pt-BR")}</p><h4>A sua ${label} é ${value}.</h4></div><strong>${value}</strong></header><div class="number-role-copy"><p>${role.opening}</p><p>${role.bridge}</p></div><div class="number-voice"><h5>${profile.title}</h5><p>${profile.light}</p><p>${profile.shadow}</p><p class="number-truth">${profile.truth}</p></div><div class="arcana-integration-grid"><section class="arcana-panel"><span>ARCANO ${value}</span><h5>${profile.arcana}</h5><p>No lado luz, você provavelmente reconhece e conduz essa força.</p><p>No lado sombra, pode ser ela quem conduz você sem que perceba.</p></section><section class="integration-panel"><span>🔹 EU POSSO TE AJUDAR A INTEGRAR</span><p>Quando essa energia pesa, a gente não trata você como um problema. Eu olho para o lugar onde o dom se feriu. ${profile.integration}</p><p>Na Radiestesia eu investigo a prioridade. Na Mesa, reorganizo repetições. Nas vivências, a gente transforma compreensão em travessia. E nas reprogramações, trabalha a voz interna que continua conduzindo a mesma resposta.</p></section></div></article>`;}).join("");
  const pyramid=`<div class="letters-row">${result.letters.map(escapeHtml).join(" ")}</div>${result.pyramid.map((row)=>`<div>${row.join("  ")}</div>`).join("")}`;
  const sequences=result.sequences.length?`<div class="sequence-alert found"><p class="section-label">SEQUÊNCIAS ENCONTRADAS</p><h4>O SEU NOME POSSUI PONTOS DE CONCENTRAÇÃO.</h4><p class="sequence-intro">Sequência não é condenação. É força repetida até virar hábito, proteção ou ferida. A sua consciência continua podendo mudar a forma dessa verdade.</p><div class="sequence-list">${result.sequences.map((hit)=>{const reading=sequenceReadings[hit.number];return `<article class="sequence-deep-card"><header><strong>${String(hit.number).repeat(Math.min(hit.length,6))}</strong><span>Linha ${hit.line} • ${hit.length} repetições reais</span></header><h5>${reading.title} <em>(${reading.shadow})</em></h5><p class="sequence-lived">${reading.lived}</p><div class="sequence-block"><b>O que essa força pode bloquear</b><p>${reading.block}</p></div><div class="sequence-layers">${reading.layers.map((layer)=>`<p>${layer}</p>`).join("")}</div><div class="sequence-gift"><b>O dom que ficou preso dentro da ferida</b><p>${reading.gift}</p></div><div class="sequence-treatment"><b>🔹 EU POSSO TE AJUDAR A INTEGRAR</b><p>${reading.treatment}</p><p>Primeiro eu escuto o campo e a sua história; depois a gente reconhece o cuidado que respeita o seu tempo.</p></div></article>`;}).join("")}</div><p class="truth-note">A repetição é real no cálculo. A forma como ela vive em você é uma verdade mutável.</p></div>`:`<div class="sequence-alert clear"><p class="section-label">SEQUÊNCIAS</p><h4>NENHUMA REPETIÇÃO TRIPLA APARECEU NA SUA PIRÂMIDE.</h4><p>Eu examinei todas as linhas e não encontrei uma concentração 111 a 999. Isso não significa equilíbrio total. Ausências, excessos, Dívidas, conflitos e o nome de uso ainda podem revelar onde a energia pesa.</p><p>Às vezes o bloqueio não grita numa sequência. Ele aparece na falta, na compensação e no modo como você aprendeu a viver um número.</p></div>`;
  document.querySelector("#quiz-panel").innerHTML=`${progressHeader(100,"Seu mini mapa")}<div class="result-view"><div class="result-opening"><p class="section-label">ESTE É O SEU PRIMEIRO ESPELHO</p><h3>${escapeHtml(firstName.toLocaleUpperCase("pt-BR"))}, O SEU NOME JÁ COMEÇOU A FALAR.</h3><p>Este é um recorte do mapa completo. Eu não vou reduzir você a cinco números. Vou abrir cada um como uma força viva e depois mostrar onde o nome repete aquilo que a sua vida talvez já esteja tentando resolver.</p></div><div class="number-results">${numbers}</div><div class="deep-number-stack">${deepNumbers}</div><div class="pyramid-result"><div class="pyramid-copy"><p class="section-label">PIRÂMIDE DA VIDA</p><h4>ÁPICE ${result.apex}</h4><p>Eu examinei todas as linhas. Uma sequência só existe quando o mesmo número aparece três ou mais vezes seguidas na mesma linha.</p></div><div class="pyramid-visual">${pyramid}</div></div>${sequences}<div class="secondary-signals"><article><span>Números ausentes</span><strong>${result.missing.length?result.missing.join(" • "):"Nenhum de 1 a 8"}</strong><p>Matérias que pedem experiência consciente.</p></article><article><span>Tendências ocultas</span><strong>${result.tendencies.length?result.tendencies.map((x)=>`${x.value} × ${x.count}`).join(" • "):"Nenhuma concentração ≥ 4"}</strong><p>São excessos na linha original, não sequências.</p></article></div><article class="human-crossing"><p class="section-label">O NÚMERO ENCONTROU A SUA HISTÓRIA</p><h4>Você chegou falando de ${escapeHtml(state.answers.area.toLocaleLowerCase("pt-BR"))}.</h4><p>A repetição que mais cansa é “${escapeHtml(state.answers.repetition.toLocaleLowerCase("pt-BR"))}” e, sob pressão, você tende a “${escapeHtml(state.answers.pressure.toLocaleLowerCase("pt-BR"))}”. É aí que eu começaria a escutar o seu mapa.</p></article><div class="result-cta"><p class="section-label">O MINI MAPA MOSTRA A PORTA. O MAPA COMPLETO MOSTRA O CAMINHO.</p><h4>EU POSSO INVESTIGAR ISSO COM VOCÊ.</h4><p>Na leitura completa, eu abro Lições e Dívidas Cármicas, leio cada sequência, testo correções e mostro qual tratamento conversa com o que apareceu.</p><button class="primary-button contact-button" id="result-contact">FALAR DIRETAMENTE COM RARI</button><p class="cta-helper">Ao tocar, o resumo do seu mini mapa já entra na conversa que será aberta comigo no WhatsApp.</p></div></div>`;
  document.querySelector("#result-contact").addEventListener("click",()=>{const sequenceText=result.sequences.length?result.sequences.map((hit)=>`${String(hit.number).repeat(3)} na linha ${hit.line}`).join(", "):"nenhuma sequência tripla encontrada";const message=`Olá, Rari! Fiz o mini mapa no seu site e quero compreender melhor o que apareceu.\n\nNome: ${state.birthName}\nExpressão: ${result.expression}\nDestino: ${result.destiny}\nMissão: ${result.mission}\nÁpice: ${result.apex}\nPirâmide: ${sequenceText}\n\nMinha questão central: ${state.answers.centralQuestion}`;window.open(whatsappUrl(message),"_blank","noopener,noreferrer");});
  document.querySelector("#mini-mapa").scrollIntoView({behavior:"smooth"});
}

function openQuiz(){document.querySelector("#quiz-invitation").classList.add("hidden");document.querySelector("#quiz-panel").classList.remove("hidden");renderIdentity();setTimeout(()=>document.querySelector("#mini-mapa").scrollIntoView({behavior:"smooth"}),40);}
function openService(key){
  const service=services[key]; if(!service)return; const root=document.querySelector("#service-detail-root");
  root.innerHTML=`<article class="service-detail ${service.tone}" id="atendimento-aberto"><button class="service-close" type="button" aria-label="Fechar detalhes">FECHAR ×</button><div class="service-threshold"><span>✦</span><p>Você abriu o campo de <strong>${service.title}</strong>. Leia devagar. Perceba não apenas o que faz sentido, mas o que se movimenta em você enquanto lê.</p></div><p class="section-label">${service.number} | ${service.title}</p><h3>${service.opening}</h3><div class="service-offer"><div><span>INVESTIMENTO</span><strong>${service.investment}</strong></div><div><span>TEMPO E FORMATO</span><p>${service.duration}</p></div><div><span>O QUE ESTÁ INCLUÍDO</span><p>${service.includes}</p></div></div><div class="service-detail-grid"><section><span>QUANDO ESTE CUIDADO CHAMA VOCÊ</span><p>${service.forYou}</p></section><section><span>COMO EU TRABALHO COM VOCÊ</span><p>${service.process}</p></section><section><span>O MOVIMENTO QUE BUSCAMOS</span><p>${service.movement}</p></section></div><div class="service-journey"><p class="section-label">A TRAVESSIA DESTE ATENDIMENTO</p>${service.journey.map(([title,copy],index)=>`<section><b>${String(index+1).padStart(2,"0")}</b><div><h4>${title}</h4><p>${copy}</p></div></section>`).join("")}</div><div class="service-receive"><div><p class="section-label">O QUE VOCÊ RECEBE</p><ul>${service.deliverables.map((item)=>`<li>${item}</li>`).join("")}</ul></div><aside><p class="section-label">DEPOIS DA TRAVESSIA</p><p>${service.aftercare}</p></aside></div><div class="service-final-call"><p>Se alguma parte de você reconheceu este cuidado, você não precisa chegar com tudo resolvido. Chegue com verdade. Eu vou escutar o que está acontecendo antes de sugerir qualquer caminho.</p><a class="primary-button service-whatsapp" href="${whatsappUrl(`Olá, Rari! Li sobre ${service.title} (${service.investment}) no seu site. ${service.action} e quero conversar com você para entender se este cuidado combina com o que estou vivendo.`)}" target="_blank" rel="noreferrer">${service.action} PELO WHATSAPP</a><p class="service-autonomy">A ferramenta não vem antes da pessoa. O sagrado não retira a sua autonomia.</p></div></article>`;
  root.querySelector(".service-close").addEventListener("click",()=>{root.innerHTML="";});
  setTimeout(()=>root.querySelector(".service-detail")?.scrollIntoView({behavior:"smooth",block:"center"}),40);
}
document.querySelectorAll("[data-open-quiz]").forEach((button)=>button.addEventListener("click",openQuiz));
document.querySelectorAll("[data-whatsapp]").forEach((link)=>{link.href=whatsappUrl(link.dataset.whatsapp);link.target="_blank";link.rel="noreferrer";});
document.querySelectorAll("[data-service-key]").forEach((button)=>button.addEventListener("click",()=>openService(button.dataset.serviceKey)));
