const whatsappNumber = "5521975003419";
const whatsappUrl = (message) => `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;

const state = {
  step: "identity", birthName: "", dailyName: "", birthDate: "",
  answers: { area: "", repetition: "", pressure: "", energy: "", nameFeeling: "", desire: "", readiness: "", centralQuestion: "" }
};

const groups = { 1: "AIJQY", 2: "BKR", 3: "CGLS", 4: "DMT", 5: "EHN", 6: "UVWXÇ", 7: "OZ", 8: "FP" };
const baseValues = {};
Object.entries(groups).forEach(([value, letters]) => [...letters].forEach((letter) => { baseValues[letter] = Number(value); }));
const accents = {
  Á:["A","add",2], É:["E","add",2], Í:["I","add",2], Ó:["O","add",2], Ú:["U","add",2],
  Ã:["A","add",3], Õ:["O","add",3], Â:["A","add",7], Ê:["E","add",7], Ô:["O","add",7],
  À:["A","double",0], È:["E","double",0], Ì:["I","double",0], Ò:["O","double",0], Ù:["U","double",0],
  Ä:["A","double",0], Ë:["E","double",0], Ï:["I","double",0], Ö:["O","double",0], Ü:["U","double",0]
};
const profiles = {
  1:{title:"autoria e começo",light:"Você abre caminhos, decide e inaugura movimentos.",shadow:"pode tentar resolver tudo sozinho e transformar autonomia em isolamento.",arcana:"O Mago"},
  2:{title:"escuta e vínculo",light:"Você percebe nuances, aproxima pessoas e lê o que existe entre as palavras.",shadow:"pode se adaptar demais e esquecer de perguntar o que você deseja.",arcana:"A Sacerdotisa"},
  3:{title:"voz e criação",light:"Você transforma sensação em palavra, beleza, presença e expressão.",shadow:"pode falar muito sem se revelar ou silenciar por medo de não ser compreendido.",arcana:"A Imperatriz"},
  4:{title:"estrutura e construção",light:"Você dá corpo às ideias e cria caminhos que conseguem permanecer.",shadow:"responsabilidade pode virar rigidez, controle e cobrança para dar conta de tudo.",arcana:"O Imperador"},
  5:{title:"movimento e liberdade",light:"Você renova ambientes, aprende pela experiência e faz a vida circular.",shadow:"liberdade pode virar dispersão, excesso ou dificuldade de permanecer.",arcana:"O Hierofante"},
  6:{title:"cuidado e pertencimento",light:"Você cria beleza, acolhimento e responsabilidade afetiva.",shadow:"amor pode se confundir com obrigação, culpa ou necessidade de salvar.",arcana:"Os Enamorados"},
  7:{title:"profundidade e direção",light:"Você investiga, atravessa aparências e procura uma verdade que tenha raiz.",shadow:"profundidade pode virar desconfiança, distância ou recolhimento excessivo.",arcana:"O Carro"},
  8:{title:"poder e materialização",light:"Você administra força, recursos e escolhas com potência de realização.",shadow:"merecimento, controle e resultado podem ocupar espaço demais.",arcana:"A Justiça"},
  9:{title:"síntese e encerramento",light:"Você enxerga além do óbvio, compreende travessias e transforma experiência em consciência.",shadow:"pode carregar histórias encerradas e sentir um cansaço antigo por dentro.",arcana:"O Eremita"}
};
const sequenceMeanings = {
  1:"identidade, iniciativa e o direito de ocupar o próprio lugar",2:"sensibilidade, vínculo, espera e necessidade de aprovação",3:"voz, expressão e tudo o que procura uma saída verdadeira",4:"controle, responsabilidade, trabalho e estruturas que se tornaram peso",5:"liberdade, mudança, impulso e dificuldade de permanecer",6:"família, cuidado, culpa e a fronteira entre amar e carregar",7:"espiritualidade, silêncio, confiança e processos vividos sozinho",8:"poder, dinheiro, merecimento e relação com a força material",9:"encerramentos, doação e ciclos que precisam ser devolvidos"
};

function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]); }
function reduce(value) { let result = Math.abs(Number(value)); while (result > 9) result = String(result).split("").reduce((sum, digit) => sum + Number(digit), 0); return result; }
function letterValue(letter) { const upper = letter.toLocaleUpperCase("pt-BR"); if (baseValues[upper]) return baseValues[upper]; if (!accents[upper]) return 0; const [baseLetter, mode, amount] = accents[upper]; const base = baseValues[baseLetter]; return mode === "double" ? base * 2 : base + amount; }
function isVowel(letter) { const clean = letter.toLocaleUpperCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g, ""); return "AEIOU".includes(clean); }
function buildPyramid(values) { if (!values.length) return []; const rows = [values.map(reduce)]; while (rows.at(-1).length > 1) { const row = rows.at(-1); rows.push(row.slice(0,-1).map((value,index) => reduce(value + row[index+1]))); } return rows; }
function findSequences(rows) { const hits=[]; rows.forEach((row,rowIndex)=>{ let start=0; while(start<row.length){ let end=start+1; while(end<row.length && row[end]===row[start]) end++; if(end-start>=3) hits.push({number:row[start],line:rowIndex+1,length:end-start}); start=end; } }); return hits; }
function calculate(name,date) {
  const letters=[...name].filter((char)=>letterValue(char)>0); const values=letters.map(letterValue);
  const vowels=letters.reduce((sum,char)=>sum+(isVowel(char)?letterValue(char):0),0); const consonants=letters.reduce((sum,char)=>sum+(!isVowel(char)?letterValue(char):0),0);
  const expression=values.reduce((sum,value)=>sum+value,0); const destiny=date.replace(/\D/g,"").split("").reduce((sum,digit)=>sum+Number(digit),0); const pyramid=buildPyramid(values);
  const counts=values.map(reduce).reduce((acc,value)=>{acc[value]=(acc[value]||0)+1;return acc;},{});
  return {letters,pyramid,sequences:findSequences(pyramid),motivation:reduce(vowels),impression:reduce(consonants),expression:reduce(expression),destiny:reduce(destiny),mission:reduce(reduce(expression)+reduce(destiny)),apex:pyramid.at(-1)?.[0]||0,missing:Array.from({length:8},(_,i)=>i+1).filter((value)=>!counts[value]),tendencies:Object.entries(counts).filter(([,count])=>count>=4).map(([value,count])=>({value:Number(value),count}))};
}
function formatBirthDate(value) { const digits=value.replace(/\D/g,"").slice(0,8); if(digits.length<=2)return digits; if(digits.length<=4)return `${digits.slice(0,2)}/${digits.slice(2)}`; return `${digits.slice(0,2)}/${digits.slice(2,4)}/${digits.slice(4)}`; }

function progressHeader(percent, title="Questionário de escuta") { return `<div class="progress-header"><span>${title}</span><span>${percent}%</span></div><div class="progress-track"><i style="width:${percent}%"></i></div>`; }
function optionGroup(legend,name,options){ return `<fieldset class="question-group"><legend>${legend}</legend><div class="option-grid">${options.map((option)=>`<label class="option"><input type="radio" name="${name}" value="${escapeHtml(option)}"><span>${escapeHtml(option)}</span></label>`).join("")}</div></fieldset>`; }
function setError(message){ const old=document.querySelector(".quiz-error"); if(old) old.remove(); if(message){ const error=document.createElement("div"); error.className="quiz-error"; error.textContent=message; document.querySelector(".quiz-form")?.prepend(error); } }
function readRadio(name){ return document.querySelector(`input[name="${name}"]:checked`)?.value || ""; }

function renderIdentity(){
  state.step="identity"; const panel=document.querySelector("#quiz-panel");
  panel.innerHTML=`${progressHeader(25)}<form class="quiz-form" id="identity-form"><div class="form-opening"><span class="step-number">01</span><div><h3>Primeiro, eu preciso encontrar a raiz do seu nome.</h3><p>Escreva exatamente como está no registro. Acentos alteram o cálculo.</p></div></div><label class="text-field"><span>Nome completo de nascimento</span><input id="birth-name" required placeholder="Ex.: Rari Couto Favaro" value="${escapeHtml(state.birthName)}"></label><label class="text-field"><span>Nome que você usa diariamente</span><input id="daily-name" placeholder="Se for diferente" value="${escapeHtml(state.dailyName)}"></label><label class="text-field"><span>Data de nascimento</span><input id="birth-date" type="text" inputmode="numeric" autocomplete="bday" maxlength="10" required placeholder="Digite apenas os números" pattern="[0-9]{2}/[0-9]{2}/[0-9]{4}" value="${escapeHtml(state.birthDate)}"></label><p class="field-helper">Digite 24041988. Eu coloco as barras para você.</p><button class="primary-button wide">CONTINUAR A ESCUTA</button></form>`;
  const dateField=document.querySelector("#birth-date"); dateField.addEventListener("input",()=>{dateField.value=formatBirthDate(dateField.value);});
  document.querySelector("#identity-form").addEventListener("submit",(event)=>{event.preventDefault();state.birthName=document.querySelector("#birth-name").value.trim();state.dailyName=document.querySelector("#daily-name").value.trim();state.birthDate=document.querySelector("#birth-date").value.trim();if(!state.birthName||!/^\d{2}\/\d{2}\/\d{4}$/.test(state.birthDate)){setError("Escreva o nome completo e a data no formato 24/04/1988.");return;}renderListening();});
}

function renderListening(){
  state.step="listening"; const panel=document.querySelector("#quiz-panel");
  panel.innerHTML=`${progressHeader(50)}<form class="quiz-form" id="listening-form"><div class="form-opening"><span class="step-number">02</span><div><h3>Agora eu quero aproximar o cálculo da vida que você está vivendo.</h3><p>Não existe resposta certa. Existe aquilo que está vivo.</p></div></div>${optionGroup("1. Qual área da sua vida mais pede cuidado hoje?","area",["Amor e relações","Trabalho e dinheiro","Família e ancestralidade","Voz e autoestima","Espiritualidade","Direção de vida"])}${optionGroup("2. Qual repetição mais cansa você?","repetition",["Carrego tudo sozinho","Começo e não sustento","Me calo para evitar conflito","Trabalho muito e recebo pouco","Repito relações parecidas","Não consigo encerrar ciclos"])}${optionGroup("3. Quando a pressão aumenta, o que você costuma fazer?","pressure",["Tento controlar tudo","Me isolo","Cuido de todos","Fujo ou me distraio","Paraliso","Reajo e depois me arrependo"])}${optionGroup("4. Como está sua energia neste momento?","energy",["Cansada","Acelerada","Dispersa","Pesada","Sensível","Pronta para mudar"])}<div class="form-navigation"><button type="button" class="back-button" id="back-identity">VOLTAR</button><button class="primary-button">CONTINUAR</button></div></form>`;
  document.querySelector("#back-identity").addEventListener("click",renderIdentity);
  document.querySelector("#listening-form").addEventListener("submit",(event)=>{event.preventDefault();["area","repetition","pressure","energy"].forEach((key)=>state.answers[key]=readRadio(key));if(["area","repetition","pressure","energy"].some((key)=>!state.answers[key])){setError("Escolha uma resposta em cada pergunta para continuar.");return;}renderDirection();});
}

function renderDirection(){
  state.step="direction"; const panel=document.querySelector("#quiz-panel");
  panel.innerHTML=`${progressHeader(75)}<form class="quiz-form" id="direction-form"><div class="form-opening"><span class="step-number">03</span><div><h3>Última camada: o que você está pronto para reconhecer?</h3><p>É aqui que o nome encontra a escolha.</p></div></div>${optionGroup("5. Como você se sente ao ouvir o próprio nome?","nameFeeling",["Representado","Distante","Em conflito","Pesado","Curioso","Nunca pensei nisso"])}${optionGroup("6. O que você mais deseja compreender no mapa?","desire",["Minha missão","Meus bloqueios","Minha ancestralidade","Minha prosperidade","Meus relacionamentos","A força do meu nome"])}${optionGroup("7. Se o mapa apontar uma mudança, como você se sente?","readiness",["Pronto para agir","Quero compreender primeiro","Tenho medo de mudar","Preciso de acompanhamento"])}<label class="text-field"><span>8. Se eu estivesse diante de você agora, qual pergunta você me faria?</span><textarea id="central-question" required rows="4" placeholder="Escreva do seu jeito. Não precisa parecer bonito.">${escapeHtml(state.answers.centralQuestion)}</textarea></label><div class="form-navigation"><button type="button" class="back-button" id="back-listening">VOLTAR</button><button class="primary-button">ABRIR MEU MINI MAPA</button></div></form>`;
  document.querySelector("#back-listening").addEventListener("click",renderListening);
  document.querySelector("#direction-form").addEventListener("submit",(event)=>{event.preventDefault();["nameFeeling","desire","readiness"].forEach((key)=>state.answers[key]=readRadio(key));state.answers.centralQuestion=document.querySelector("#central-question").value.trim();if(["nameFeeling","desire","readiness"].some((key)=>!state.answers[key])||!state.answers.centralQuestion){setError("Escolha as três respostas e escreva a pergunta que está viva em você.");return;}renderResult();});
}

function renderResult(){
  state.step="result"; const result=calculate(state.birthName,state.birthDate); const profile=profiles[result.expression]; const firstName=(state.dailyName||state.birthName).split(/\s+/)[0]||"você";
  const numbers=[["Motivação",result.motivation],["Impressão",result.impression],["Expressão",result.expression],["Destino",result.destiny],["Missão",result.mission]].map(([label,value])=>`<article><span>${label}</span><strong>${value}</strong></article>`).join("");
  const pyramid=`<div class="letters-row">${result.letters.map(escapeHtml).join(" ")}</div>${result.pyramid.map((row)=>`<div>${row.join("  ")}</div>`).join("")}`;
  const sequences=result.sequences.length?`<div class="sequence-alert found"><p class="section-label">SEQUÊNCIAS ENCONTRADAS</p><h4>O SEU NOME POSSUI PONTOS DE CONCENTRAÇÃO.</h4><div class="sequence-list">${result.sequences.map((hit)=>`<article><strong>${String(hit.number).repeat(Math.min(hit.length,6))}</strong><span>Linha ${hit.line} • ${hit.length} repetições</span><p>Essa concentração toca ${sequenceMeanings[hit.number]}.</p></article>`).join("")}</div><p class="truth-note">Isso não é uma condenação. É uma força acumulada que precisa ser compreendida antes de qualquer correção.</p></div>`:`<div class="sequence-alert clear"><p class="section-label">SEQUÊNCIAS</p><h4>NENHUMA REPETIÇÃO TRIPLA APARECEU NA SUA PIRÂMIDE.</h4><p>Isso não significa equilíbrio total. Ausências, excessos, Dívidas Cármicas e o nome de uso aparecem na leitura completa.</p></div>`;
  document.querySelector("#quiz-panel").innerHTML=`${progressHeader(100,"Seu mini mapa")}<div class="result-view"><div class="result-opening"><p class="section-label">ESTE É O SEU PRIMEIRO ESPELHO</p><h3>${escapeHtml(firstName.toLocaleUpperCase("pt-BR"))}, O SEU NOME JÁ COMEÇOU A FALAR.</h3><p>Este é um recorte do mapa completo. O cálculo abre o terreno. A sua história mostra onde precisamos caminhar.</p></div><div class="number-results">${numbers}</div><article class="living-reading"><div class="reading-number">${result.expression}</div><div><p class="section-label">SUA EXPRESSÃO</p><h4>${profile.title}</h4><p>${profile.light}</p><p class="shadow-copy">Na sombra, ${profile.shadow}</p><p class="arcana-copy">Arcano ${result.expression}: <strong>${profile.arcana}</strong></p></div></article><div class="pyramid-result"><div class="pyramid-copy"><p class="section-label">PIRÂMIDE DA VIDA</p><h4>ÁPICE ${result.apex}</h4><p>Eu examinei todas as linhas. Uma sequência só existe quando o mesmo número aparece três ou mais vezes seguidas na mesma linha.</p></div><div class="pyramid-visual">${pyramid}</div></div>${sequences}<div class="secondary-signals"><article><span>Números ausentes</span><strong>${result.missing.length?result.missing.join(" • "):"Nenhum de 1 a 8"}</strong><p>Matérias que pedem experiência consciente.</p></article><article><span>Tendências ocultas</span><strong>${result.tendencies.length?result.tendencies.map((x)=>`${x.value} × ${x.count}`).join(" • "):"Nenhuma concentração ≥ 4"}</strong><p>São excessos na linha original, não sequências.</p></article></div><article class="human-crossing"><p class="section-label">O NÚMERO ENCONTROU A SUA HISTÓRIA</p><h4>Você chegou falando de ${escapeHtml(state.answers.area.toLocaleLowerCase("pt-BR"))}.</h4><p>A repetição que mais cansa é “${escapeHtml(state.answers.repetition.toLocaleLowerCase("pt-BR"))}” e, sob pressão, você tende a “${escapeHtml(state.answers.pressure.toLocaleLowerCase("pt-BR"))}”. É aí que eu começaria a escutar o seu mapa.</p></article><div class="result-cta"><p class="section-label">O MINI MAPA MOSTRA A PORTA. O MAPA COMPLETO MOSTRA O CAMINHO.</p><h4>EU POSSO INVESTIGAR ISSO COM VOCÊ.</h4><p>Na leitura completa, eu abro Lições e Dívidas Cármicas, leio cada sequência, testo correções e mostro qual tratamento conversa com o que apareceu.</p><button class="primary-button contact-button" id="result-contact">FALAR DIRETAMENTE COM RARI</button><p class="cta-helper">Ao tocar, o resumo do seu mini mapa já entra na conversa que será aberta comigo no WhatsApp.</p></div></div>`;
  document.querySelector("#result-contact").addEventListener("click",()=>{const sequenceText=result.sequences.length?result.sequences.map((hit)=>`${String(hit.number).repeat(3)} na linha ${hit.line}`).join(", "):"nenhuma sequência tripla encontrada";const message=`Olá, Rari! Fiz o mini mapa no seu site e quero compreender melhor o que apareceu.\n\nNome: ${state.birthName}\nExpressão: ${result.expression}\nDestino: ${result.destiny}\nMissão: ${result.mission}\nÁpice: ${result.apex}\nPirâmide: ${sequenceText}\n\nMinha questão central: ${state.answers.centralQuestion}`;window.open(whatsappUrl(message),"_blank","noopener,noreferrer");});
  document.querySelector("#mini-mapa").scrollIntoView({behavior:"smooth"});
}

function openQuiz(){document.querySelector("#quiz-invitation").classList.add("hidden");document.querySelector("#quiz-panel").classList.remove("hidden");renderIdentity();setTimeout(()=>document.querySelector("#mini-mapa").scrollIntoView({behavior:"smooth"}),40);}
document.querySelectorAll("[data-open-quiz]").forEach((button)=>button.addEventListener("click",openQuiz));
document.querySelectorAll("[data-whatsapp]").forEach((link)=>{link.href=whatsappUrl(link.dataset.whatsapp);link.target="_blank";link.rel="noreferrer";});
document.querySelectorAll("[data-service]").forEach((link)=>{const [title,action]=link.dataset.service.split("|");link.href=whatsappUrl(`Olá, Rari! Vi ${title} no seu site. ${action}. Você pode me explicar como funciona?`);link.target="_blank";link.rel="noreferrer";});
